### ISSUE TITLE
training label of logic circuit  is not good

### ISSUE THREAD

**Issue by kaikai529** [Hattomo/kaikai_AI#98]
## Description
Training label of logic circuit is not good.
we should be change training label( 0 or 1 ) to array([1 0 0 0],[0 1 0 0],[0 0 1 0],[0 0 0 1])
#### Step1
- [x] or
- [x] and
- [x] nand
- [x] xor
- [x] w_not
#### step2
- [x] adopt analysis tools

**Comment by Hattomo** [comment]
I'm working on this
